---
- name: Deploy MERN app using Docker
  hosts: ec2
  become: true

  vars:
    backend_repo: "kalanichethana/mern-backend"
    frontend_repo: "kalanichethana/mern-frontend"
    image_tag: "latest"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Enable & start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull backend image
      community.docker.docker_image:
        name: "{{ backend_repo }}"
        tag: "{{ image_tag }}"
        source: pull

    - name: Pull frontend image
      community.docker.docker_image:
        name: "{{ frontend_repo }}"
        tag: "{{ image_tag }}"
        source: pull

    - name: Remove old backend container
      community.docker.docker_container:
        name: backend
        state: absent
        force_kill: true

    - name: Remove old frontend container
      community.docker.docker_container:
        name: frontend
        state: absent
        force_kill: true

    - name: Run backend container
      community.docker.docker_container:
        name: backend
        image: "{{ backend_repo }}:{{ image_tag }}"
        state: started
        restart_policy: always
        published_ports:
          - "4000:4000"

    - name: Run frontend container
      community.docker.docker_container:
        name: frontend
        image: "{{ frontend_repo }}:{{ image_tag }}"
        state: started
        restart_policy: always
        published_ports:
          - "3000:80"
